trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: boneguard-secrets
  - name: MAVEN_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.m2/repository
  - name: MAVEN_OPTS
    value: -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)

steps:
  - task: Cache@2
    displayName: Cache Maven dependencies
    inputs:
      key: 'maven | "$(Agent.OS)" | boneguard-service/pom.xml'
      restoreKeys: |
        maven | "$(Agent.OS)"
        maven
      path: $(MAVEN_CACHE_FOLDER)

  - task: JavaToolInstaller@0
    displayName: Use Java 17
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: x64
      jdkSourceOption: PreInstalled

  - task: Maven@4
    displayName: Build - mvn package (boneguard-service)
    inputs:
      mavenPomFile: boneguard-service/pom.xml
      goals: package
      options: '-DskipTests $(MAVEN_OPTS)'
      publishJUnitResults: false
      javaHomeOption: JDKVersion
      jdkVersionOption: '1.17'

  - task: Maven@4
    displayName: Test - mvn test (boneguard-service)
    inputs:
      mavenPomFile: boneguard-service/pom.xml
      goals: test
      options: '-Dtest=!BoneguardServiceApplicationTests $(MAVEN_OPTS)'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: JDKVersion
      jdkVersionOption: '1.17'
    env:
      DB_USERNAME: $(DB_USERNAME)
      DB_PASSWORD: $(DB_PASSWORD)
      JWT_SECRET: $(JWT_SECRET)
      GROQ_API_KEY: $(GROQ_API_KEY)
      RABBITMQ_HOST: $(RABBITMQ_HOST)
      RABBITMQ_USER: $(RABBITMQ_USER)
      RABBITMQ_PASS: $(RABBITMQ_PASS)
      RABBITMQ_VHOST: $(RABBITMQ_VHOST)

  - task: Maven@4
    displayName: Build - mvn package (notification-service)
    inputs:
      mavenPomFile: notification-service/pom.xml
      goals: package
      options: '-DskipTests $(MAVEN_OPTS)'
      publishJUnitResults: false
      javaHomeOption: JDKVersion
      jdkVersionOption: '1.17'

  - task: CopyFiles@2
    displayName: Copy boneguard JAR to staging
    inputs:
      sourceFolder: boneguard-service/target
      contents: 'boneguard-service-*.jar'
      targetFolder: $(Build.ArtifactStagingDirectory)/boneguard

  - task: CopyFiles@2
    displayName: Copy notification JAR to staging
    inputs:
      sourceFolder: notification-service/target
      contents: 'notification-service-*.jar'
      targetFolder: $(Build.ArtifactStagingDirectory)/notification

  - task: PublishBuildArtifacts@1
    displayName: Publish artifact boneguard-app
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)/boneguard
      artifactName: boneguard-app
      publishLocation: Container

  - task: PublishBuildArtifacts@1
    displayName: Publish artifact notification-app
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)/notification
      artifactName: notification-app
      publishLocation: Container